interface frontenddata{
    gif:string,
    img:string,
    name: string,
    link:string,
    github:string,
    techstack:string[],
}

export const FullStackapi:frontenddata[] =[
    {
        gif:"/p1.gif",
        img:"/p4.png",
        name:"TinyClo",
        link:"https://kudosware-testing.vercel.app/",
        github:"https://github.com/Arpit10110/kudosware-testing",
        techstack:["JavaScript","React.js","Node.js","Express.js","MongodB","ShopifyAdmin"]
    },
    {
        gif:"/p9.gif",
        img:"/p9.png",
        name:"ChaiCircle",
        link:"https://chaicircle.vercel.app",
        github:"https://github.com/Arpit10110/ChaiCircle",
        techstack:["React.js","TypeScript","Socket.io","MongodB","Express","Material-UI"]
    },
    {
        gif:"/p2.gif",
        img:"/p6.png",
        name:"Kalakaari-Ai",
        link:"https://kalakaari-ai.vercel.app/",
        github:"https://github.com/Arpit10110/Kalakaari-AI",
        techstack:["Next.js","Aos","Razorpay","MongodB","JavaScript","Material-UI"]
    },
    {
        gif:"/p3.gif",
        img:"/p7.png",
        name:"Ghumakkad",
        link:"https://ghumakad.vercel.app/",
        github:"https://github.com/Arpit10110/HealthBridge-frontend",
        techstack:["Next.js","Aos","Razorpay","MongodB","TypeScript","Acerternity","Material-UI"]
    },
    {
        gif:"/p4.gif",
        img:"/p5.png",
        name:"HealthBridge",
        link:"https://healthbridges.vercel.app/",
        github:"https://github.com/Arpit10110/HealthBridge-frontend",
        techstack:["JavaScript","React.js","Firebase","Node.js","Express.js","MongodB"]
    },
]